/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package employeeapp.view;

import java.util.Calendar;
import java.util.GregorianCalendar;
/**
 *
 * @author Khanyisile
 */
public final class MainJFrame extends javax.swing.JFrame {

    /**
     * Creates new form MainJFrame
     */
    public MainJFrame() {
        initComponents();
        currentDate();
    }
    
    //Stores current date and time
    public void currentDate(){
        Calendar cal = new GregorianCalendar();
        int day = cal.get(Calendar.DAY_OF_MONTH);
        int month = cal.get(Calendar.MONTH);
        int year = cal.get(Calendar.YEAR);
        
        lbl_date.setText(day+"/"+(month +1)+"/"+year);
        
        int second = cal.get(Calendar.SECOND);
        int minute = cal.get(Calendar.MINUTE);
        int hour = cal.get(Calendar.HOUR);
        
        lbl_time.setText(hour+":"+ (minute)+":"+second);
      
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        manageEmployeesjButton = new javax.swing.JButton();
        manageDepjButton = new javax.swing.JButton();
        managePayjButton = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        lbl_date = new javax.swing.JMenu();
        lbl_time = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Employee Management System");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(190, 50, 358, 28);

        manageEmployeesjButton.setBackground(java.awt.SystemColor.controlHighlight);
        manageEmployeesjButton.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        manageEmployeesjButton.setText("Manage Employees");
        manageEmployeesjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manageEmployeesjButtonActionPerformed(evt);
            }
        });
        jPanel1.add(manageEmployeesjButton);
        manageEmployeesjButton.setBounds(290, 200, 170, 24);

        manageDepjButton.setBackground(java.awt.SystemColor.controlHighlight);
        manageDepjButton.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        manageDepjButton.setText("Manage Departments");
        manageDepjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manageDepjButtonActionPerformed(evt);
            }
        });
        jPanel1.add(manageDepjButton);
        manageDepjButton.setBounds(290, 260, 170, 24);

        managePayjButton.setBackground(java.awt.SystemColor.controlHighlight);
        managePayjButton.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        managePayjButton.setText("Manage Payroll");
        managePayjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                managePayjButtonActionPerformed(evt);
            }
        });
        jPanel1.add(managePayjButton);
        managePayjButton.setBounds(290, 320, 170, 24);

        jLabel2.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Welcome! Please select an option below.");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(230, 130, 286, 17);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/employeeapp/Images/EMS.jpg"))); // NOI18N
        jLabel3.setText("jLabel3");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(0, 0, 760, 450);

        jMenuBar1.setBackground(java.awt.SystemColor.controlHighlight);

        jMenu1.setText("File");
        jMenuBar1.add(jMenu1);

        lbl_date.setText("Date");
        jMenuBar1.add(lbl_date);

        lbl_time.setText("Time");
        jMenuBar1.add(lbl_time);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 758, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 428, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Make the Employee frame visible
    private void manageEmployeesjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manageEmployeesjButtonActionPerformed
        ManageEmpJFrame manageEmpJFrame = new ManageEmpJFrame();
        manageEmpJFrame.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_manageEmployeesjButtonActionPerformed
    
    //Display Department Frame 
    private void manageDepjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manageDepjButtonActionPerformed
        ManageDepJFrame manageDepJFrame = new ManageDepJFrame();
        manageDepJFrame.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_manageDepjButtonActionPerformed

    //Display Payrolls Frame
    private void managePayjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_managePayjButtonActionPerformed
        ManagePayJFrame managePayJFrame = new ManagePayJFrame();
        managePayJFrame.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_managePayjButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new MainJFrame().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JMenu lbl_date;
    private javax.swing.JMenu lbl_time;
    private javax.swing.JButton manageDepjButton;
    private javax.swing.JButton manageEmployeesjButton;
    private javax.swing.JButton managePayjButton;
    // End of variables declaration//GEN-END:variables
}
